import { clientRuntimeConfig, defaultClientConfig } from "./client_config.js";

export function emptySlot() {
  return { petalType: 0, rarity: 0 };
}

export function slotHasItem(slot) {
  return slot && slot.petalType > 0 && slot.rarity > 0;
}

export const dom = {
  canvas: document.getElementById("game"),
  authPanel: document.getElementById("authPanel"),
  wsUrlInput: document.getElementById("wsUrl"),
  accountInput: document.getElementById("account"),
  passwordInput: document.getElementById("password"),
  registerModeInput: document.getElementById("registerMode"),
  connectBtn: document.getElementById("connectBtn"),
  authStatus: document.getElementById("authStatus"),
  deathOverlay: document.getElementById("deathOverlay"),
  deathSource: document.getElementById("deathSource"),
  deathLoot: document.getElementById("deathLoot"),
  reviveBtn: document.getElementById("reviveBtn"),
  deathCloseBtn: document.getElementById("deathCloseBtn"),
  quickActions: document.getElementById("quickActions"),
  quickBackpackBtn: document.getElementById("quickBackpackBtn"),
  quickTalentBtn: document.getElementById("quickTalentBtn"),
  quickCraftBtn: document.getElementById("quickCraftBtn"),
  quickTalentPoints: document.getElementById("quickTalentPoints"),
  chatPanel: document.getElementById("chatPanel"),
  chatChannels: document.getElementById("chatChannels"),
  chatLog: document.getElementById("chatLog"),
  chatHint: document.getElementById("chatHint"),
  chatInput: document.getElementById("chatInput"),
  petalInfoTooltip: document.getElementById("petalInfoTooltip"),
  sliderPanel: document.getElementById("sliderPanel"),
  sliderTitle: document.getElementById("sliderTitle"),
  sliderValue: document.getElementById("sliderValue"),
  sliderInput: document.getElementById("sliderInput"),
  sliderCloseBtn: document.getElementById("sliderCloseBtn"),
  consolePanel: document.getElementById("consolePanel"),
  debugInfo: document.getElementById("debugInfo"),
  consoleLog: document.getElementById("consoleLog"),
  consoleInput: document.getElementById("consoleInput"),
  backpackPanel: document.getElementById("backpackPanel"),
  backpackCloseBtn: document.getElementById("backpackCloseBtn"),
  craftPanel: document.getElementById("craftPanel"),
  craftCloseBtn: document.getElementById("craftCloseBtn"),
  craftStage: document.getElementById("craftStage"),
  craftResultSlot: document.getElementById("craftResultSlot"),
  craftList: document.getElementById("craftList"),
  craftSelection: document.getElementById("craftSelection"),
  craftChance: document.getElementById("craftChance"),
  craftOnceBtn: document.getElementById("craftOnceBtn"),
  talentPanel: document.getElementById("talentPanel"),
  talentCloseBtn: document.getElementById("talentCloseBtn"),
  talentPointsLabel: document.getElementById("talentPoints"),
  talentTree: document.getElementById("talentTree"),
  primarySlots: document.getElementById("primarySlots"),
  secondarySlots: document.getElementById("secondarySlots"),
  inventoryList: document.getElementById("inventoryList"),
  inventoryStacking: document.getElementById("inventoryStacking"),
  inventorySearch: document.getElementById("inventorySearch"),
};

dom.ctx = dom.canvas.getContext("2d");

export const state = {
  ws: null,
  connected: false,
  authenticated: false,
  receiveBuffer: new Uint8Array(),
  entities: new Map(),
  playerId: 0,
  ownerEntityId: 0,
  ownerLevel: 1,
  ownerExpProgress: 0,
  snapshotId: -1,
  serverTickInterval: clientRuntimeConfig.serverTickInterval,
  ownerPredictionTiming: {
    expectedSnapshotInterval: clientRuntimeConfig.expectedSnapshotInterval,
    snapshotInterval: clientRuntimeConfig.expectedSnapshotInterval,
    simulationScale: 1,
    samples: [],
    lastSnapshotAt: 0,
    lastSnapshotId: -1,
  },
  viewRadius: 0,
  map: null,
  mapName: "",
  mapDisplayName: "",
  loginMapName: clientRuntimeConfig.loginMapDefaultName,
  loginMapX: clientRuntimeConfig.loginMapDefaultX,
  loginMapY: clientRuntimeConfig.loginMapDefaultY,
  loginMapHorizon: clientRuntimeConfig.loginMapDefaultHorizon,
  mapLoadToken: 0,
  mapLoadPromise: null,
  ownerSlots: Array.from({ length: 5 }, () => emptySlot()),
  secondarySlots: Array.from({ length: 5 }, () => emptySlot()),
  inventory: [],
  runCollectionBaseline: null,
  runCollectionBaselinePending: true,
  squadMemberNames: new Set(),
  slotTxSeq: 0,
  slotTransactions: [],
  ownerStateLoaded: false,
  inventoryLoaded: false,
  inventoryStacked: false,
  inventorySearchQuery: "",
  chats: [],
  selectedSlot: 0,
  camera: { x: 0, y: 0 },
  keys: new Set(),
  mouse: { x: 0, y: 0, seen: false, inUi: false },
  localMoveInput: { x: 0, y: 0 },
  ownerMovementMultiplier: 1,
  predictionDebug: {
    errorDistance: 0,
    speedScale: 1,
    tickScale: 1,
    snapshotInterval: clientRuntimeConfig.expectedSnapshotInterval,
    staleTime: 0,
    snapped: false,
  },
  screenShake: { x: 0, y: 0 },
  particles: [],
  keyboardControl: false,
  mobileControlMode: "auto",
  clientConfig: { ...defaultClientConfig },
  attacking: false,
  defending: false,
  digging: false,
  lastInput: {
    x: 99,
    y: 99,
    attacking: false,
    defending: false,
    digging: false,
  },
  sendTimer: 1,
  lastFrameTime: performance.now(),
  fps: 0,
  consoleOpen: false,
  chatOpen: false,
  chatFilters: { local: true, global: true, whisper: true, server: true },
  lastChatRenderAt: 0,
  debugHitbox: false,
  altFeaturesEnabled: false,
  deathOverlayClosed: false,
  wasOwnerDead: false,
  slider: null,
  minimapMode: "local",
  backpackOpen: false,
  craftOpen: false,
  talentOpen: false,
  talentPoints: 0,
  talents: [],
  craftSlots: Array.from({ length: 5 }, () => null),
  craftSource: null,
  craftPhase: "idle",
  craftResult: null,
  craftBurstUntil: 0,
  craftSpinStarted: 0,
  petalInfoHoverElement: null,
  drag: null,
  suppressClickUntil: 0,
  canvasWidth: 0,
  canvasHeight: 0,
  dpr: 1,
};
